/* tslint:disable */
/* eslint-disable */
/**
 * Wise API
 * API for Wise Assistant Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmotionRecord
 */
export interface EmotionRecord {
    /**
     * 
     * @type {number}
     * @memberof EmotionRecord
     */
    emotion: number;
    /**
     * 
     * @type {number}
     * @memberof EmotionRecord
     */
    confidence: number;
    /**
     * 
     * @type {Date}
     * @memberof EmotionRecord
     */
    readonly createdAt: Date;
}

/**
 * Check if a given object implements the EmotionRecord interface.
 */
export function instanceOfEmotionRecord(value: object): value is EmotionRecord {
    if (!('emotion' in value) || value['emotion'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function EmotionRecordFromJSON(json: any): EmotionRecord {
    return EmotionRecordFromJSONTyped(json, false);
}

export function EmotionRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmotionRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'emotion': json['emotion'],
        'confidence': json['confidence'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function EmotionRecordToJSON(value?: Omit<EmotionRecord, 'created_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'emotion': value['emotion'],
        'confidence': value['confidence'],
    };
}

