/* tslint:disable */
/* eslint-disable */
/**
 * Wise API
 * API for Wise Assistant Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmotionRecordAggregate
 */
export interface EmotionRecordAggregate {
    /**
     * 
     * @type {string}
     * @memberof EmotionRecordAggregate
     */
    emotionName: string;
    /**
     * 
     * @type {number}
     * @memberof EmotionRecordAggregate
     */
    result: number;
}

/**
 * Check if a given object implements the EmotionRecordAggregate interface.
 */
export function instanceOfEmotionRecordAggregate(value: object): value is EmotionRecordAggregate {
    if (!('emotionName' in value) || value['emotionName'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function EmotionRecordAggregateFromJSON(json: any): EmotionRecordAggregate {
    return EmotionRecordAggregateFromJSONTyped(json, false);
}

export function EmotionRecordAggregateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmotionRecordAggregate {
    if (json == null) {
        return json;
    }
    return {
        
        'emotionName': json['emotion__name'],
        'result': json['result'],
    };
}

export function EmotionRecordAggregateToJSON(value?: EmotionRecordAggregate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'emotion__name': value['emotionName'],
        'result': value['result'],
    };
}

