/* tslint:disable */
/* eslint-disable */
/**
 * Wise API
 * API for Wise Assistant Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedEmotionRecord
 */
export interface PatchedEmotionRecord {
    /**
     * 
     * @type {number}
     * @memberof PatchedEmotionRecord
     */
    emotion?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedEmotionRecord
     */
    confidence?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedEmotionRecord
     */
    readonly createdAt?: Date;
}

/**
 * Check if a given object implements the PatchedEmotionRecord interface.
 */
export function instanceOfPatchedEmotionRecord(value: object): value is PatchedEmotionRecord {
    return true;
}

export function PatchedEmotionRecordFromJSON(json: any): PatchedEmotionRecord {
    return PatchedEmotionRecordFromJSONTyped(json, false);
}

export function PatchedEmotionRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedEmotionRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'emotion': json['emotion'] == null ? undefined : json['emotion'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function PatchedEmotionRecordToJSON(value?: Omit<PatchedEmotionRecord, 'created_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'emotion': value['emotion'],
        'confidence': value['confidence'],
    };
}

