/* tslint:disable */
/* eslint-disable */
/**
 * Wise API
 * API for Wise Assistant Backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EmotionRecordAggregate,
} from '../models/index';
import {
    EmotionRecordAggregateFromJSON,
    EmotionRecordAggregateToJSON,
} from '../models/index';

export interface AggregateListRequest {
    func: AggregateListFuncEnum;
    createdAt?: Date;
    createdAtDateGt?: Date;
    createdAtDateRange?: Array<Date>;
    createdAtRange?: Array<Date>;
    createdAtTimeGt?: string;
    createdAtTimeRange?: Array<string>;
    createdAtYear?: number;
    emotion?: number;
}

/**
 * 
 */
export class AggregateApi extends runtime.BaseAPI {

    /**
     */
    async aggregateListRaw(requestParameters: AggregateListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EmotionRecordAggregate>>> {
        if (requestParameters['func'] == null) {
            throw new runtime.RequiredError(
                'func',
                'Required parameter "func" was null or undefined when calling aggregateList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['createdAt'] != null) {
            queryParameters['created_at'] = (requestParameters['createdAt'] as any).toISOString();
        }

        if (requestParameters['createdAtDateGt'] != null) {
            queryParameters['created_at__date__gt'] = (requestParameters['createdAtDateGt'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['createdAtDateRange'] != null) {
            queryParameters['created_at__date__range'] = requestParameters['createdAtDateRange']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['createdAtRange'] != null) {
            queryParameters['created_at__range'] = requestParameters['createdAtRange']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['createdAtTimeGt'] != null) {
            queryParameters['created_at__time__gt'] = requestParameters['createdAtTimeGt'];
        }

        if (requestParameters['createdAtTimeRange'] != null) {
            queryParameters['created_at__time__range'] = requestParameters['createdAtTimeRange']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['createdAtYear'] != null) {
            queryParameters['created_at__year'] = requestParameters['createdAtYear'];
        }

        if (requestParameters['emotion'] != null) {
            queryParameters['emotion'] = requestParameters['emotion'];
        }

        if (requestParameters['func'] != null) {
            queryParameters['func'] = requestParameters['func'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/aggregate/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EmotionRecordAggregateFromJSON));
    }

    /**
     */
    async aggregateList(requestParameters: AggregateListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EmotionRecordAggregate>> {
        const response = await this.aggregateListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const AggregateListFuncEnum = {
    Average: 'average',
    Count: 'count'
} as const;
export type AggregateListFuncEnum = typeof AggregateListFuncEnum[keyof typeof AggregateListFuncEnum];
